<a href="https://colab.research.google.com/github/Bhavya-131529/CSE-273/blob/main/CSE_273.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:

marks = np.array([65, 30, 5, 45, 80, 10, 50, 75])
st= (marks >= 50).astype(int)
print(marks)
print(st)

[65 30  5 45 80 10 50 75]
[1 0 0 0 1 0 1 1]


In [ ]:
marks[marks < 40] = 1
print(marks)

[65  1  1 45 80  1 50 75]


In [ ]:
avg = np.mean(marks)

if avg >= 85:
  print("A")
elif avg >= 70:
  print("B")
elif avg >= 50:
  print("C")
elif avg < 50:
  print("D")

In [ ]:
avg = np.where(marks < 50, 1, np.where(marks < 70, 2, np.where(marks < 85, 3, 0)))
print(avg)

[2 1 1 1 3 1 2 3]


In [ ]:
electricity = np.random.randint(120, 650, size=(4, 7))
print(electricity)

[[549 286 350 133 146 521 503]
 [571 195 412 344 460 259 328]
 [465 173 179 235 350 221 375]
 [584 527 319 564 621 293 289]]


In [ ]:
import pandas as pd

In [ ]:
s=pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64


In [ ]:
print(s[0])

10


In [ ]:
s=pd.Series([10,20,30],index=["a","b","c"])
print(s)

a    10
b    20
c    30
dtype: int64


In [ ]:
print(s["a"])

10


In [ ]:
print(s[0])

10


/tmp/ipython-input-287792665.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])


In [ ]:
data={'Math': 90,'Physic': 85,'Chemistry': 83}
marks=pd.Series(data)
print(marks)

Math         90
Physic       85
Chemistry    83
dtype: int64


In [ ]:
data={"Name": {"Aman","Krish","Karan"},
      "Age": {22,23,24},
      "Marks": {86,94,37}}
print(data)
type(data)

{'Name': {'Aman', 'Krish', 'Karan'}, 'Age': {24, 22, 23}, 'Marks': {86, 37, 94}}


dict

In [ ]:
data={"Name": ["Aman","Krish","Karan"],
      "Age": [22,23,24],
      "Marks": [86,94,37]}
marks=pd.DataFrame(data)
print(marks) #pandas automatically adds a default index: This is called a RangeIndex(starts from 0 by default)

    Name  Age  Marks
0   Aman   22     86
1  Krish   23     94
2  Karan   24     37


In [ ]:
#we can also add custom index in pandas dataframe
marks=pd.DataFrame(data,index=["S1","S2","S3"])
print(marks)

     Name  Age  Marks
S1   Aman   22     86
S2  Krish   23     94
S3  Karan   24     37


In [ ]:
#if we are setting implace = true it means we are changing the original object itself,if we do this without implace a new dataframe is created.
marks.set_index("Name",inplace=True)
print(marks)

       Age  Marks
Name             
Aman    22     86
Krish   23     94
Karan   24     37


In [ ]:
df=pd.DataFrame({
    "Name": ["Aman","Krish","Karan"],
      "Age": [22,23,24],
      "Marks": [86,94,37]
})
print(df)

    Name  Age  Marks
0   Aman   22     86
1  Krish   23     94
2  Karan   24     37


In [ ]:
df.head()
# as the no of rows is less than 5 so the output of both 0f head and df tail will be identical.

Name  Age  Marks
0   Aman   22     86
1  Krish   23     94
2  Karan   24     37

In [ ]:
df.tail()

Name  Age  Marks
0   Aman   22     86
1  Krish   23     94
2  Karan   24     37

In [ ]:
df=pd.DataFrame({
    "Name": ["Aman","Krish","Karan","Sameer","Bhavya"],
      "Age": [22,23,24,27,32],
      "Marks": [86,94,37,74,92]
})
print(df)

     Name  Age  Marks
0    Aman   22     86
1   Krish   23     94
2   Karan   24     37
3  Sameer   27     74
4  Bhavya   32     92


Name  Age  Marks
0   Aman   22     86
1  Krish   23     94

In [ ]:
df.head()

Name  Age  Marks
0    Aman   22     86
1   Krish   23     94
2   Karan   24     37
3  Sameer   27     74
4  Bhavya   32     92

In [ ]:
df.head(2)

Name  Age  Marks
0   Aman   22     86
1  Krish   23     94

In [ ]:
df.tail(2)

Name  Age  Marks
3  Sameer   27     74
4  Bhavya   32     92

In [ ]:
df.tail()

Name  Age  Marks
0    Aman   22     86
1   Krish   23     94
2   Karan   24     37
3  Sameer   27     74
4  Bhavya   32     92

In [ ]:
df.shape

(5, 3)

In [ ]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    5 non-null      object
 1   Age     5 non-null      int64 
 2   Marks   5 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes


In [ ]:
df.describe()

Age      Marks
count   5.000000   5.000000
mean   25.600000  76.600000
std     4.037326  23.469129
min    22.000000  37.000000
25%    23.000000  74.000000
50%    24.000000  86.000000
75%    27.000000  92.000000
max    32.000000  94.000000

In [ ]:
df["Name"]

0      Aman
1     Krish
2     Karan
3    Sameer
4    Bhavya
Name: Name, dtype: object

In [ ]:
df[["Name","Marks"]]

Name  Marks
0    Aman     86
1   Krish     94
2   Karan     37
3  Sameer     74
4  Bhavya     92

In [ ]:
df[df["Marks"]>85]

Name  Age  Marks
0    Aman   22     86
1   Krish   23     94
4  Bhavya   32     92

In [ ]:
df[(df["Age"] > 10) & (df["Marks"] > 52)]

Name  Age  Marks
0    Aman   22     86
1   Krish   23     94
3  Sameer   27     74
4  Bhavya   32     92

In [ ]:
df.sort_values(by="Marks")

Name  Age  Marks
2   Karan   24     37
3  Sameer   27     74
0    Aman   22     86
4  Bhavya   32     92
1   Krish   23     94

In [ ]:
df.sort_values(by="Marks",ascending=False)

Name  Age  Marks
1   Krish   23     94
4  Bhavya   32     92
0    Aman   22     86
3  Sameer   27     74
2   Karan   24     37

In [ ]:
df["Age"].value_counts()

Age
22    1
23    1
24    1
27    1
32    1
Name: count, dtype: int64

In [ ]:
# updating the dataset will null values
df=pd.DataFrame({
    "Name": ["Aman","Krish","Karan","Sameer",None,"Bhavya"],
      "Age": [22,23,None,24,27,32],
      "Marks": [86,94,None,37,74,92]
})
df

Name   Age  Marks
0    Aman  22.0   86.0
1   Krish  23.0   94.0
2   Karan   NaN    NaN
3  Sameer  24.0   37.0
4    None  27.0   74.0
5  Bhavya  32.0   92.0

In [ ]:
df.isnull()

Name    Age  Marks
0  False  False  False
1  False  False  False
2  False   True   True
3  False  False  False
4   True  False  False
5  False  False  False

In [ ]:
df.isnull().sum()

Name     1
Age      1
Marks    1
dtype: int64

In [ ]:
df.dropna()

Name   Age  Marks
0    Aman  22.0   86.0
1   Krish  23.0   94.0
3  Sameer  24.0   37.0
5  Bhavya  32.0   92.0

In [ ]:
print(df)

     Name   Age  Marks
0    Aman  22.0   86.0
1   Krish  23.0   94.0
2   Karan   NaN    NaN
3  Sameer  24.0   37.0
4    None  27.0   74.0
5  Bhavya  32.0   92.0


In [ ]:
cleaned_df=df.dropna()
print(cleaned_df)

     Name   Age  Marks
0    Aman  22.0   86.0
1   Krish  23.0   94.0
3  Sameer  24.0   37.0
5  Bhavya  32.0   92.0


In [ ]:
import pandas as pd

df = pd.DataFrame({
    'EmployeeName': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Department': ['HR', 'Engineering', 'Marketing', 'Sales', 'Material Dep'],
    'Role': ['Analyst', 'Manager', 'Employee', 'Senior Eng', 'Senior Eng'],
    'Salary': [60000, 80000, 75000, 65000, 90000],
    'Experience': [2, 5, 3, 4, 8],
    'Score':[95,75,68,95,89]
})
print(df)

  EmployeeName    Department        Role  Salary  Experience  Score
0        Alice            HR     Analyst   60000           2     95
1          Bob   Engineering     Manager   80000           5     75
2      Charlie     Marketing    Employee   75000           3     68
3        David         Sales  Senior Eng   65000           4     95
4          Eve  Material Dep  Senior Eng   90000           8     89


In [ ]:
average= df.groupby('Department')['Salary'].mean()
print(average)

Department
Engineering     80000.0
HR              60000.0
Marketing       75000.0
Material Dep    90000.0
Sales           65000.0
Name: Salary, dtype: float64


In [ ]:
avg_score_by_role = df.groupby('Role')['Score'].mean()
print(avg_score_by_role)

Role
Analyst       95.0
Employee      68.0
Manager       75.0
Senior Eng    92.0
Name: Score, dtype: float64


In [ ]:
non_null = df.groupby('Department')['Score'].count()
print(non_null)

Department
Engineering     1
HR              1
Marketing       1
Material Dep    1
Sales           1
Name: Score, dtype: int64


In [ ]:
total_records_by_department = df.groupby('Department').size()
print(total_records_by_department)

Department
Engineering     1
HR              1
Marketing       1
Material Dep    1
Sales           1
dtype: int64


In [ ]:
summary= df.groupby('Department').agg(average_salary=('Salary', 'mean'), non_null=('Score', 'count'), total=('EmployeeName', 'size'))
print('Departmental Summary:')
print(summary)

Departmental Summary:
              average_salary  non_null_scores  total_records
Department                                                  
Engineering          80000.0                1              1
HR                   60000.0                1              1
Marketing            75000.0                1              1
Material Dep         90000.0                1              1
Sales                65000.0                1              1


In [ ]:
sutable